services:
  - type: web
    name: todo-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: 84606b72d94829e337e75fe014eb94d8847031e9429dc44f5522ff50620ca403
      - key: JWT_EXPIRE
        value: 30d
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        sync: false
      # @https://todo-project-xi-three.vercel.app/
      - key: FRONTEND_URL
        value: https://todo-project-xi-three.vercel.app
      # Existing frontend URL for reference
      - key: FRONTEND_URL
        value: https://to-do-frontend-ljd2.vercel.app 